# Generated by Django 4.2.1 on 2023-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='jurusan',
            field=models.TextField(choices=[('Akuntasi', 'Akuntasi'), ('Manajemen', 'Manajemen'), ('Perdagangan Internasional', 'perdagangan Internasionak'), ('Informatika', 'Informatika'), ('Industri', 'Industri'), ('Informasi', 'Informasi'), ('Elektro', 'Elektro'), ('Mesin', 'Mesin'), ('Sipil', 'Sipil'), ('Jepang', 'Jepang'), ('Inggris', 'Inggris'), ('Desain Grafis', 'Desain Grafis'), ('Multimedia', 'Multimedia'), ('Perpustakaan & Sains Informasi', 'Perpustakaan & Sains Informasi'), ('Produksi Film & Televisi', 'Produksi Film & Televisi')],  max_length=100),
        ),
        migrations.AddField(
            model_name='anggota',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
