# Generated by Django 4.2.1 on 2023-05-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_anggota_jenis_kelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='nama',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='nim',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan')], max_length=100)),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField()),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buku')),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_nama', to='app.anggota', to_field='nama')),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_nim', to='app.anggota', to_field='nim')),
            ],
        ),
    ]
