# Generated by Django 4.2.1 on 2023-05-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_anggota_nama_alter_anggota_nim_peminjaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Contemporary', 'Contemporary'), ('Dystopian', 'Dystopian'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Paranormal', 'Paranormal'), ('Historical fiction', 'Historical fiction'), ('Science Fiction', 'Science Fiction'), ('Childrens', 'Childrens'), ('Memoir', 'Memoir'), ('Cookbook', 'Cookbook'), ('Art', 'Art'), ('Self-help', 'Self-help'), ('Development', 'Development'), ('Motivational', 'Motivational'), ('History', 'History'), ('Travel', 'Travel'), ('Humor', 'Humor'), ('Families', 'Families'), ('Guide', 'Guide')], max_length=120),
        ),
    ]
