# Generated by Django 4.2.1 on 2023-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_buku_judul_buku_alter_buku_kode_buku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='judul_buku',
            field=models.TextField(max_length=120),
        ),
    ]
