# Generated by Django 4.2.1 on 2023-05-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_buku_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='jurusan',
            field=models.TextField(choices=[('Akuntasi', 'Akuntasi'), ('Manajemen', 'Manajemen'), ('Perdagangan Internasional', 'perdagangan Internasional'), ('Informatika', 'Informatika'), ('Industri', 'Industri'), ('Informasi', 'Informasi'), ('Elektro', 'Elektro'), ('Mesin', 'Mesin'), ('Sipil', 'Sipil'), ('Jepang', 'Jepang'), ('Inggris', 'Inggris'), ('Desain Grafis', 'Desain Grafis'), ('Multimedia', 'Multimedia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='buku',
            name='genre',
            field=models.TextField(choices=[('Fantasy', 'Fantasy'), ('Fantasy fiction', 'Fantasy fiction'), ('Science fiction', 'Science fiction'), ('English fiction', 'English fiction'), ('Adventure stories', 'Adventure stories'), ('True Crime', 'True Crime'), ('Education', 'Education'), ('Social Science', 'Social Science'), ('Business & Economics', 'Business & Economics'), ('Horror', 'Horror'), ('Philosophy', 'Philosophy'), ('Paranormal', 'Paranormal'), ('Historical fiction', 'Historical fiction'), ('Science', 'Science'), ("Children's stories", "Children's stories"), ('Authors', 'Authors'), ('Juvenile Fiction', 'Juvenile Fiction'), ('Art', 'Art'), ('Self-Help', 'Self-Help'), ('Family & Relationships', 'Family & Relationships'), ('Sports & Recreation', 'Sports & Recreation'), ('Health & Fitness', 'Health & Fitness'), ('History', 'History'), ('Travel', 'Travel'), ('Humor', 'Humor'), ('Families', 'Families'), ('Animals', 'Animals'), ('Fiction', 'Fiction'), ('Religion', 'Religion'), ('Psychology', 'Psychology'), ('Biography & Autobiography', 'Biography & Autobiography'), ('Juvenile Fiction', 'Juvenile Fiction'), ('Detective and mystery stories', 'Detective and mystery stories')], max_length=120),
        ),
    ]
