# Generated by Django 4.2.1 on 2023-06-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_buku_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_kembali',
            field=models.DateField(blank=True, null=True),
        ),
    ]
