# Generated by Django 4.2.1 on 2023-06-02 08:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_peminjaman_tanggal_kembali'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='ticket',
            field=models.CharField(default=app.models.peminjaman.randomless, max_length=12),
        ),
    ]
