# Generated by Django 4.2.1 on 2023-06-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_peminjaman_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='fakultas',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='tanggal_lahir',
        ),
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('anggota_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.anggota')),
                ('fakultas', models.CharField(choices=[('EKONOMI DAN BISNIS', 'EKONOMI DAN BISNIS'), ('TEKNIK', 'TEKNIK'), ('ILMU BUDAYA', 'ILMU BUDAYA'), ('DESAIN KOMUNIKASI DAN VISUAL', 'DESAIN KOMUNIKASI DAN VISUAL')], max_length=100)),
                ('jurusan', models.TextField(choices=[('Akuntasi', 'Akuntasi'), ('Manajemen', 'Manajemen'), ('Perdagangan Internasional', 'perdagangan Internasional'), ('Informatika', 'Informatika'), ('Industri', 'Industri'), ('Informasi', 'Informasi'), ('Elektro', 'Elektro'), ('Mesin', 'Mesin'), ('Sipil', 'Sipil'), ('Jepang', 'Jepang'), ('Inggris', 'Inggris'), ('Desain Grafis', 'Desain Grafis'), ('Multimedia', 'Multimedia')], max_length=100)),
                ('jenis_kelamin', models.TextField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
            ],
            bases=('app.anggota',),
        ),
    ]
